#! /usr/bin/env python3

import sys
from nml.editors import kate, notepadpp

def run():
    if len(sys.argv) != 2 or sys.argv[1] not in ('kate', 'notepadpp'):
        print("gen_editor: Incorrect arguments found.")
        print("Usage: gen_editor [ kate | notepadpp ]")
        sys.exit(1)

    if sys.argv[1] == 'kate':
        kate.run()
    elif sys.argv[1] == 'notepadpp':
        notepadpp.run()
    else:
        assert False, "Unknown editor name encountered."

    sys.exit(0)

if __name__ == '__main__':
    run()
